1、创建一个长度为10的一维全为0的ndarray对象，然后让第5个元素等于1

In [6]:
import numpy as np
n = np.zeros(10)
n[4] = 1
n

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

2、创建一个元素为从10到49的ndarray对象

In [5]:
n=np.arange(10,50)
n

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

3、将第2题的所有元素位置反转

In [6]:
n[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

4、使用np.random.random创建一个10*10的ndarray对象，并打印出最大最小元素

In [10]:
n = np.random.random(size=(10,10))
nmin, nmax = n.min(), n.max()
display(nmin, nmax)

0.0008713538414192312

0.9993526381616968

5、创建一个10*10的ndarray对象，且矩阵边界全为1，里面全为0

In [11]:
n = np.ones((10, 10))
n[1:-1, 1:-1] = 0
n

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

6、创建一个每一行都是从0到4的5*5矩阵

In [21]:
# 方法1
n = np.arange(0,25,1)
n.resize((5,5))
n[1:5] = n[0] 
n

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [24]:
# 方法二 利用ndarray的广播机制
np.arange(0, 5)  + np.zeros((5,5), dtype='int')

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

7、创建一个范围在(0,1)之间的长度为12的等差数列

In [26]:
n = np.linspace(0, 1, 12)
n

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

8、创建一个长度为10的随机数组并排序

In [27]:
n = np.random.random(10)
n.sort()
n

array([0.0285138 , 0.06486675, 0.1259646 , 0.1889158 , 0.45264663,
       0.50190353, 0.50277799, 0.59781875, 0.86759346, 0.97186204])

9、创建一个长度为10的随机数组并将最大值替换为0

In [33]:
n = np.random.randint(10,100,10)
print(n)
np.argmax(n)
n[np.argmax(n)] = 0
n

[71 99 42 32 98 33 11 10 83 25]


array([71,  0, 42, 32, 98, 33, 11, 10, 83, 25])

10、如何根据第3列来对一个5*5矩阵排序？

In [41]:
n = np.random.randint(0,10, size=(5,5))
n

array([[3, 4, 0, 6, 9],
       [9, 2, 8, 4, 5],
       [0, 7, 9, 7, 4],
       [8, 8, 1, 4, 9],
       [5, 4, 6, 1, 7]])

In [42]:
sort_index = np.argsort(n[: ,2])  # 获取第三列数据 并排序 然后获取排序的索引
sort_index

array([0, 3, 4, 1, 2])

In [44]:
n[sort_index]

array([[3, 4, 0, 6, 9],
       [8, 8, 1, 4, 9],
       [5, 4, 6, 1, 7],
       [9, 2, 8, 4, 5],
       [0, 7, 9, 7, 4]])

11、给定一个4维矩阵，如何得到最后两维的和？

In [76]:
#首先对numpy中axis取值进行说明：一维数组时axis=0，二维数组时axis=0，1，
#维数越高，则axis可取的值越大，数组n维时，axis=0，1，…，n。为了方便下面的理解，
#我们这样看待：在numpy中数组都有着[]标记，则axis=0对应着最外层的[]，axis=1对应第二外层的[]，以此类推，axis=n对应第n外层的[]。 
# axis=0 代表垂直行的方向执行函数 0  1  2  3 代表 4个维度   2，3可以用 -2 -1 表示
n=np.random.randint(0,10,size=(2,3,2,2))
n

array([[[[9, 9],
         [9, 4]],

        [[2, 7],
         [6, 5]],

        [[5, 7],
         [4, 8]]],


       [[[6, 0],
         [9, 8]],

        [[6, 7],
         [7, 7]],

        [[7, 5],
         [1, 5]]]])

In [82]:
#n.sum(axis=-1) 
n.sum(axis=(-1, -2))

array([[31, 20, 24],
       [23, 27, 18]])

12、给定数组[1, 2, 3, 4, 5]，如何得到在这个数组的每个元素之间插入3个0后的新数组？

In [10]:
n = [1, 2, 3, 4, 5]
n = np.vstack(n)
n

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [16]:
n2 = np.zeros((5,3), dtype='int32')
n3=np.concatenate((n, n2), axis=1)

In [18]:
np.hstack(n3)

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0])

13、给定一个二维矩阵，如何交换其中两行的元素？

In [19]:
n = np.random.randint(0, 20, size=(3,4))
n

array([[16,  6, 12, 11],
       [14, 13,  9,  2],
       [ 2, 13, 17, 15]])

In [20]:
n[0], n[1] = n[1], n[0]
n

array([[14, 13,  9,  2],
       [14, 13,  9,  2],
       [ 2, 13, 17, 15]])

14、创建一个100000长度的随机数组，使用两种方法对其求三次方，并比较所用时间

In [29]:
n = np.random.randint(0, 10, 10000)
n

array([7, 6])

In [32]:
%timeit np.power(n, 3)

769 ns ± 9.18 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [33]:
%timeit n**3

783 ns ± 5.56 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [34]:
n2 = np.dot(n,n)
%timeit np.dot(n,n2)

865 ns ± 31.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


15、创建一个5*3随机矩阵和一个3*2随机矩阵，求矩阵积

In [35]:
n1 = np.random.randint(0,5, size=(5,3))
n2 = np.random.randint(0,5, size=(3,2))
np.dot(n1, n2)

array([[ 6,  4],
       [15,  8],
       [11,  8],
       [ 8, 12],
       [ 2,  4]])

16、矩阵的每一行的元素都减去该行的平均值

In [37]:
n = np.random.randint(0,10, size=(5,3))
n

array([[5, 9, 8],
       [4, 4, 5],
       [7, 8, 0],
       [6, 4, 5],
       [0, 9, 9]])

In [43]:
n_mean = np.mean(n, axis=1)
n_mean

array([7.33333333, 4.33333333, 5.        , 5.        , 6.        ])

In [46]:
n2 = np.vstack(n_mean)
n2

array([[7.33333333],
       [4.33333333],
       [5.        ],
       [5.        ],
       [6.        ]])

In [47]:
n - n2

array([[-2.33333333,  1.66666667,  0.66666667],
       [-0.33333333, -0.33333333,  0.66666667],
       [ 2.        ,  3.        , -5.        ],
       [ 1.        , -1.        ,  0.        ],
       [-6.        ,  3.        ,  3.        ]])

17、打印出以下函数（要求使用np.zeros创建8*8的矩阵）：

```[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]```

In [49]:
n = np.zeros((8,8), dtype='int32')
n

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [50]:
n[1::2, ::2] = 1
n[::2, 1::2] = 1
n

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int32)

18、正则化一个5*5随机矩阵
正则的概念：假设a是矩阵中的一个元素，max/min分别是矩阵元素的最大最小值，则正则化后a = (a - min)/(max - min)

In [55]:
n = np.random.randint(0,10, size=(5,5))
n

array([[9, 2, 4, 8, 0],
       [8, 4, 2, 7, 6],
       [9, 4, 3, 1, 1],
       [6, 6, 9, 9, 8],
       [9, 0, 4, 7, 1]])

In [56]:
max, min = n.max(), n.min()
n = (n - min) / (max - min)
n

array([[1.        , 0.22222222, 0.44444444, 0.88888889, 0.        ],
       [0.88888889, 0.44444444, 0.22222222, 0.77777778, 0.66666667],
       [1.        , 0.44444444, 0.33333333, 0.11111111, 0.11111111],
       [0.66666667, 0.66666667, 1.        , 1.        , 0.88888889],
       [1.        , 0.        , 0.44444444, 0.77777778, 0.11111111]])

19、将一个一维数组转化为二进制表示矩阵。例如 [1,2,3]

```
转化为
[[0,0,1],
[0,1,0],
[0,1,1]]```

In [67]:
I = np.array([1,2,3])
A= I.reshape(-1,1)
A

array([[1],
       [2],
       [3]])

In [72]:
B = 2**np.arange(3)
B = B[::-1]
B

array([4, 2, 1])

In [101]:
M =A&B
M

array([[0, 0, 1],
       [0, 2, 0],
       [0, 2, 1]])

In [103]:
M!=0

array([[False, False,  True],
       [False,  True, False],
       [False,  True,  True]])

In [104]:
M[M!=0] = 1
M

array([[0, 0, 1],
       [0, 1, 0],
       [0, 1, 1]])

20、实现冒泡排序法

In [123]:
n = [19, 60, 66, 71, 54, 57, 1, 24, 82, 39]
for i in range(len(n)-1):
    for j in range(len(n)-i-1):
        if n[j] > n[j+1]:
            n[j], n[j+1] = n[j+1], n[j]
n

[1, 19, 24, 39, 54, 57, 60, 66, 71, 82]