In [1]:
# Basic Operations example using TensorFlow library.
# Author: Aymeric Damien
# Project: https://github.com/aymericdamien/TensorFlow-Examples/

In [1]:
import tensorflow as tf

In [2]:
# Basic constant operations
# The value returned by the constructor represents the output
# of the Constant op.
a = tf.constant(2)
b = tf.constant(3)

In [3]:
# Launch the default graph.
# 启动默认graph（流图）
with tf.Session() as sess:
    print("a: %i" % sess.run(a), "b: %i" % sess.run(b))
    print("Addition with constants: %i" % sess.run(a+b))
    print("Multiplication with constants: %i" % sess.run(a*b))
    print('10*a + 7*b: %i'%sess.run(10*a+7*b))

a: 2 b: 3
Addition with constants: 5
Multiplication with constants: 6
10*a + 7*b: 41


第一种方式，声明常量进行了算数运算
第二种方式，声明placeholder，占位符

In [4]:
# Basic Operations with variable as graph input
# The value returned by the constructor represents the output
# of the Variable op. (define as input when running session)
# tf Graph input
#占位符，值类型确定，值是多少还不知道
a = tf.placeholder(tf.int32)
b = tf.placeholder(tf.int32)
c = tf.placeholder(tf.int32)

In [5]:
# Define some operations
#定义操作，操作，原理图中的加减操作
add = tf.add(a, b)
mul = tf.multiply(a, b)
div = tf.divide(a,b)
sub = tf.subtract(a,b)

In [7]:
#进行运算的时候进行赋值

with tf.Session() as sess:
    print(sess.run(add,feed_dict={a:10,b:15}))
    print(sess.run(sub,feed_dict={a:10,b:15}))

25
-5


In [8]:
# Launch the default graph.
#启动具体操作
with tf.Session() as sess:
    # Run every operation with variable input
    print("Addition with variables: %i" % sess.run(add, feed_dict={a: 2, b: 3}))
    print("Multiplication with variables: %i" % sess.run(mul, feed_dict={a: 2, b: 3}))
    print('div : %i'%sess.run(div,feed_dict={a:14,b:7}))
    print('subtract: %i'%sess.run(sub,feed_dict = {a:1024,b:512}))

Addition with variables: 5
Multiplication with variables: 6
div : 2
subtract: 512


In [9]:
# ----------------
# More in details:
# Matrix Multiplication from TensorFlow official tutorial

# Create a Constant op that produces a 1x2 matrix.  The op is
# added as a node to the default graph.
#
# The value returned by the constructor represents the output
# of the Constant op.
#Tensor可以声明矩阵
import numpy as np
a = np.array([1,2,3,4,5,6],dtype=float).reshape((1,6))

#数据pd读取的真实数据：ndarray组成

matrix1 = tf.constant(a)

In [10]:
# Create another Constant that produces a 2x1 matrix.

b = np.linspace(-np.pi,np.pi,6,dtype=float).reshape((6,1))
matrix2 = tf.constant(b)

In [11]:
# Create a Matmul op that takes 'matrix1' and 'matrix2' as inputs.
# The returned value, 'product', represents the result of the matrix
# multiplication.

#matmul：矩阵乘法
#算数乘法multiply
#mat:matrix;mul:multipy
matmul = tf.matmul(matrix1, matrix2)
add = tf.add(matrix1,matrix2)
mul = tf.multiply(matrix1,matrix2)

In [12]:
# To run the matmul op we call the session 'run()' method, passing 'product'
# which represents the output of the matmul op.  This indicates to the call
# that we want to get the output of the matmul op back.
#
# All inputs needed by the op are run automatically by the session.  They
# typically are run in parallel.
#
# The call 'run(product)' thus causes the execution of threes ops in the
# graph: the two constants and matmul.
#
# The output of the op is returned in 'result' as a numpy `ndarray` object.

#开启会话，执行运算
with tf.Session() as sess:
    print(sess.run(matmul))
    print(sess.run(add))
    print("  ")
    print(sess.run(mul))

[[21.99114858]]
[[-2.14159265 -1.14159265 -0.14159265  0.85840735  1.85840735  2.85840735]
 [-0.88495559  0.11504441  1.11504441  2.11504441  3.11504441  4.11504441]
 [ 0.37168147  1.37168147  2.37168147  3.37168147  4.37168147  5.37168147]
 [ 1.62831853  2.62831853  3.62831853  4.62831853  5.62831853  6.62831853]
 [ 2.88495559  3.88495559  4.88495559  5.88495559  6.88495559  7.88495559]
 [ 4.14159265  5.14159265  6.14159265  7.14159265  8.14159265  9.14159265]]
  
[[ -3.14159265  -6.28318531  -9.42477796 -12.56637061 -15.70796327
  -18.84955592]
 [ -1.88495559  -3.76991118  -5.65486678  -7.53982237  -9.42477796
  -11.30973355]
 [ -0.62831853  -1.25663706  -1.88495559  -2.51327412  -3.14159265
   -3.76991118]
 [  0.62831853   1.25663706   1.88495559   2.51327412   3.14159265
    3.76991118]
 [  1.88495559   3.76991118   5.65486678   7.53982237   9.42477796
   11.30973355]
 [  3.14159265   6.28318531   9.42477796  12.56637061  15.70796327
   18.84955592]]
